version: '3.7'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=gazin

  backend:
    build: ./backend/.
    # command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "start"]
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      GAZIN_DB_HOST: postgres
      GAZIN_DB_PORT: 5432
      GAZIN_DB_USER: postgres
      GAZIN_DB_PASSWORD: gazin
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend/.
    # command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "start"]
    depends_on:
      - backend
    environment:
      NODE_ENV: development
    ports:
      - "3001:3001"