version: '3.7'
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=gazin
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5

  backend:
    build: ./backend/.
    depends_on:
        postgres:
            condition: service_healthy
            restart: true      
    environment:
        NODE_ENV: development
        GAZIN_DB_HOST: postgres
        GAZIN_DB_PORT: 5432
        GAZIN_DB_USER: postgres
        GAZIN_DB_PASSWORD: gazin
    ports:
        - "3000:3000"

  frontend:
    build: ./frontend/.
    depends_on:
        - backend
    environment:
        NODE_ENV: development
        GAZIN_SERVER_HOST: backend
    ports:
        - "3001:80"